spring:
  application:
    name: webservicetest
  datasource:
    url: jdbc:postgresql://localhost:5432/products-api
    username: dianzinha
    password: 8958
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
